# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      stg_tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'STG Tag'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Create Preprod TAG from UAT 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if : "${{github.event.inputs.stg_tag != ''}}"

        run : | 
            
            PRE_PROD_TAG="pre_prod_${{ github.event.inputs.stg_tag }}"

            
            git fetch --all
            echo "${PRE_PROD_TAG}"
            git tag "${PRE_PROD_TAG}" ${{inputs.stg_tag}} 
            git tag --list
            release_hash=$(git show-ref --hash  -- "$PRE_PROD_TAG")
            echo "RELEASE_VERSION=$release_hash" >> $GITHUB_ENV
            #PRE_PROD_TAG >> $GITHUB_ENV
            #echo "$PRE_PROD_TAG_" >> ${PRE_PROD_TAG}
            echo $RELEASE_VERSION
            echo "hash"
     
        shell: bash
        
      - name: Create Release
        if : "${{github.event.inputs.stg_tag != '' }}"
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.RELEASE_VERSION }}
          tag_name: ${{env.PRE_PROD_TAG_}}
          name: ${{env.PRE_PROD_TAG_}}
          draft: false
          prerelease: true
