name : "Create a tag after running build"

on :
 push:
     branches :
       - 'hotfix*'
       
 
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          
      - name :  Display commit hash of this runner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run : |
             echo $GITHUB_SHA
              

              
        shell: bash
        
