name: Create a preprod tag from STG tag

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      stg_tag:
        required: true
        default: ''
        description: 'STG tag'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Create Preprod TAG from UAT 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if : "${{github.event.inputs.stg_tag != ''}}"

        run : | 
            
            PRE_PROD_TAG="pre_prod_${{ github.event.inputs.stg_tag }}"

            
            git fetch --all
            echo "${PRE_PROD_TAG}"
            git tag "${PRE_PROD_TAG}" ${{inputs.stg_tag}} 
            git tag --list

            echo "$RELEASE_VERSION" >> git show-ref --hash  -- "${PRE_PROD_TAG}"
            echo "$PRE_PROD_TAG_" >> ${PRE_PROD_TAG}
      
     
        shell: bash
        
      - name: Create Release
        if : "${{github.event.inputs.stg_tag != '' }}"
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.RELEASE_VERSION }}
          tag_name: ${{env.PRE_PROD_TAG_}}
          name: ${{env.PRE_PROD_TAG_}}
          draft: false
          prerelease: true
  
    
