# This is a basic workflow that is manually triggered

name: PreProd Tag Builder

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      stg_tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'UAT Tag'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      preprod_tag:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Preprod tag'
        # Default value if no value is explicitly provided
        default: ''
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
    

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
     # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      
      - name: Create Preprod TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

        run : | 
            pwd
            ls
            #git config --global user.email "kashyap.asrc@gmail.com"
            #git config --global user.name "Release BOT"
            git fetch --all
            git --version
            git status
            
            git tag ${{inputs.preprod_tag}} ${{inputs.stg_tag}} 
            git tag --list
            git status

            echo "$RELEASE_VERSION" >> git show-ref --hash  -- ${{inputs.preprod_tag}}
      
     
        shell: bash
        
      - name: Create Release
        uses: thomaseizinger/create-release@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ env.RELEASE_VERSION }}
          tag_name: ${{inputs.preprod_tag}}
          name: ${{inputs.preprod_tag}}
          draft: false
          prerelease: true
